/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/apple_watch_series_7_-_free_watch-face_sdctm.glb 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-series-7-free-watch-face-sdctm-cf15ecbf159f42a28df5e56bdfa666bb
Title: Apple Watch Series 7 - Free Watch-Face SDC™️
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/apple_watch_series_7_-_free_watch-face_sdctm.glb"
  );
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.019, 0.026, 0.017]}
        rotation={[2.622, 0, -Math.PI / 2]}
        scale={0.001}
      >
        <mesh geometry={nodes.Object_4.geometry} material={materials.Black2} />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material.007"]}
        />
      </group>
      <group
        position={[0.001, 0.015, 0.016]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      >
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[0.001, 0.015, 0.016]}
        rotation={[1.051, 0.065, 0]}
        scale={0.001}
      >
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Black_Glossy}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.Black_Glossy2}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.Glass_Clear2}
        />
      </group>
      <group
        position={[0.001, 0.015, 0.016]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      >
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.Black_Glossy}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.Black_Glossy_TEXT}
        />
      </group>
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials["Material.008"]}
        position={[0.001, 0.015, 0.016]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["Material.006"]}
        position={[0.001, 0.015, 0.015]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.Material_2034}
        position={[0.001, 0.014, 0.016]}
        rotation={[1.051, 0.065, 0]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.Material_1898}
        position={[0.001, 0.017, 0.015]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials["Material.004"]}
        position={[0.003, 0.016, 0.016]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.Object_27.geometry}
        material={materials["Material.001"]}
        position={[0.001, 0.015, 0.016]}
        rotation={[1.051, 0, 0]}
        scale={0.001}
      />
    </group>
  );
}

useGLTF.preload("/apple_watch_series_7_-_free_watch-face_sdctm.glb");
