/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/apple_watch_series_7.glb 
Author: Gatti Mattia (https://sketchfab.com/gatti.mattia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-series-7-d8802bdcc2bb41de8e752fec0e044bf1
Title: Apple Watch Series 7
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/apple_watch_series_7.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Rubber} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Iron_Clean} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Iron_Clean} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Iron_Clean3} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_0} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Black_Glossy_TEXT} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Black2} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.material_1} position={[4.513, 149.879, 69.039]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/apple_watch_series_7.glb')
