/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/digital_watch.glb 
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/digital-watch-b6466b64dd8b495c99f24a5054491f4d
Title: Digital Watch
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/digital_watch.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group name="screen" position={[0.732, 0.002, -0.656]} rotation={[0, 1.571, 0]} scale={[1.173, 1.789, 1]}>
              <mesh name="screen_0" geometry={nodes.screen_0.geometry} material={materials.screen} />
            </group>
            <group name="screen001" position={[0.715, 0.002, -0.656]} rotation={[0, 1.571, 0]} scale={[1.173, 1.789, 1]}>
              <mesh name="screen001_0" geometry={nodes.screen001_0.geometry} material={materials.screen_with_emmision} />
            </group>
            <group name="watch" position={[0, -0.009, -0.741]} scale={[1, 2.734, 2.481]}>
              <mesh name="watch_0" geometry={nodes.watch_0.geometry} material={materials.watch} />
            </group>
            <group name="strap" position={[-0.841, 0.006, -3.898]} rotation={[0, 0.231, 0]} scale={[0.403, 1.884, 0.521]}>
              <mesh name="strap_0" geometry={nodes.strap_0.geometry} material={materials.strap} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/digital_watch.glb')
